### ISSUE TITLE
name 'Omega' is not defined

### ISSUE THREAD

**Issue by MiaoQiaowei** [ehgh/PARSRec-Explainable-Personalized-Attention-fused-Recurrent-Sequential-Recommendation#1]
```
Traceback (most recent call last):
  File "synthetic_data_generator.py", line 312, in <module>
    main()
  File "synthetic_data_generator.py", line 302, in main
    data_generator()
  File "synthetic_data_generator.py", line 201, in data_generator
    y = select_categories()
  File "synthetic_data_generator.py", line 175, in select_categories
    assert np.all(np.linalg.eigvals(omega) >= -0), 'eigen values must be all positive (semi-positive matrix). Eigen values:\n{}'.format(np.linalg.eigvals(Omega))
NameError: name 'Omega' is not defined
```

Hello, I find a bug in synthetic_data_generator.py
If I run synthetic_data_generator.sh, I will get this error
How can I fix this bug? Omega->omega? i guess
thx in advance

**Comment by ehgh** [comment]
Hi Miao,
Thank you for finding the issue. The bug is fixed now. Please kindly clone the repo and try it again. Thank you.

**Comment by ehgh** [comment]
Closing the issue. Resolved.
